// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtyezllvaqrvvqnpgpvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0eWV6bGx2YXFydnZxbnBncHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzEyODksImV4cCI6MjA2NTI0NzI4OX0.jrZ60vWlicwiKd7h5sq7K3Lw_qP7QoQWkeO6K3XhptA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);